import { View, Text, StyleSheet, ScrollView } from "react-native";
import { useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { ChatBubble } from "../../components/ChatBubble";
import journeyConfigs from "@/data/journeys";

type Message = {
  id: string;
  role: "system" | "ai" | "user";
  type: "intro" | "explanation" | "question" | "response";
  text: string;
};

export default function CoreScreen() {
  // Get journey params
  const { topic, subTopic } = useLocalSearchParams<{
    topic?: string;
    subTopic?: string;
  }>();

  // Load journey config
  const journey =
    journeyConfigs?.[topic?.toLowerCase() ?? ""]?.[
      subTopic?.toLowerCase() ?? ""
    ] ?? null;

  // Show fallback if no valid journey
  if (!journey) {
    return (
      <View style={styles.container}>
        <Text style={styles.errorText}>
          Something went wrong. Please restart your journey.
        </Text>
      </View>
    );
  }

  // Initial messages
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "1",
      role: "system",
      type: "intro",
      text: journey.intro,
    },
    {
      id: "2",
      role: "ai",
      type: "explanation",
      text: "This verse reminds us that the Quran is a book of certainty and comfort. (This will be generated by GPT in the next step.)",
    },
  ]);

  return (
    <ScrollView style={styles.container}>
      {messages.map((msg) => (
        <ChatBubble
          key={msg.id}
          sender={msg.role === "ai" ? "ai" : "user"}
          text={msg.text}
          showAvatar={msg.role === "ai" && msg.id === "2"} // Show avatar for first AI message
        />
      ))}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0e0b07",
    padding: 16,
  },
  errorText: {
    color: "#fff",
    fontSize: 16,
    textAlign: "center",
    marginTop: 24,
  },
});
